position = "Top"

[modules]
left = [ ["Workspaces", "MediaPlayer"] ]
center = [ "WindowTitle" ]
right = [ [ "Tray", "Clock", "Calendar", "Privacy", "Settings" ] ]

[[CustomModule]]
name = "Calendar"
icon = "ÔÅ≥"
command = "zenity --calendar --title=\"Calendar\""

[appearance]
font_name = "CaskaydiaCove Nerd Font"
scale_factor = 1.25
opacity = 0.9
style = "Solid"

primary_color = "#2b3b51"
secondary_color = "#39506d"
success_color = "#9ece6a"
background_color = "#192330"
text_color = "#dfdfe0"

workspace_colors = [ "#719cd6", "#719cd6" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[settings]
